### ISSUE TITLE
Chrome link in readme isn't working

### ISSUE THREAD

**Issue by jeffpaul** [pento/linkify#163]
Trying to access https://chrome.google.com/webstore/detail/linkify/bkkgikibkmalecfagnebbhbacnbhckmh gives a `This item is not available` error.  Perhaps the link updated or something needs to be fixed for the Chrome extension?  Note that I use Firefox, so things work just fine loading there but figured I'd share for the subset of folks using Chrome. 🤷🏼

**Comment by pento** [comment]
Yeah, Google blocked the listing a while ago, because I hadn't bothered with updating it to match their latest policies.

I'm working through the review process now, it should hopefully be back soon. 🙂

**Comment by pento** [comment]
It's back now, though Google never bothered to email me to say so. 🙃
